services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile  # Ahora dentro de la carpeta "docker"
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/lanzo
    depends_on:
      - mongo

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
